name: Commit Message Validation

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - testing
jobs:
  validate-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Validate commit messages
        run: |
          COMMIT_MESSAGE=$(git log --format=%s -n 1 ${{ github.sha }})
          echo $COMMIT_MESSAGE
          PATTERN="^FLTNBE-[0-9]{4}+:\s+[A-Za-z0-9]+"
          if ! [[ $COMMIT_MESSAGE =~ $PATTERN ]]; then
              echo "Error: Commit message does not match the required pattern."
            exit 1
          fi
          echo "Commit message matches the pattern."
