name: Commit Message Validation

on:
  # push:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
      - commit-message-validation
# permissions:
jobs:
  validate-commit-message:
    runs-on: ubuntu-latest

    steps:
      # - name: Check out this repo
      #   uses: actions/checkout@v2
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate commit messages
        run: |
          # Define the regex pattern for a valid commit message
          commit_message_pattern="^FLTNBE-[0-9]{4}+:\s+[A-Za-z0-9]+"

          # Get the commit messages in the pull request
          # commit_messages=$(git log --format=%B ${{ github.event.before }}..${{ github.event.after }})
          COMMIT_MESSAGE=$(git log --format=%s -n 1 ${{ github.sha }})
          echo $COMMIT_MESSAGE
          # Check each commit message against the pattern
          # for message in $commit_message; do
          for message in $COMMIT_MESSAGE; do
          # if [[ $message =~ $commit_message_pattern ]]; then
          # if [[ $message =~ ^FLTNBE-[0-9]{4}+:\s+[A-Za-z0-9]+ ]]; then
          # if [[ ! "$message" =~ $commit_message_pattern ]]; then
          if [[ ! "$COMMIT_MESSAGE" =~ $commit_message_pattern ]]; then
                echo "Invalid commit message: $message"
              exit 1
            fi
          done

          echo "All commit messages are valid."

